server:
  port: 8086


spring:
    datasource:
        url: jdbc:mysql://localhost:3306/monitor
        username: root
        password: 123456
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        initialSize: 5
        minIdle: 5
        maxActive: 20
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
    jackson:
        date-format: yyyy-MM-dd HH:mm
        time-zone: GMT+8

# ≈‰÷√mybatis-plus
mybatis-plus:
  # ≈‰÷√…®√Ëxml
  mapper-locations: classpath:mapper/*.xml
  #  µÃÂ…®√Ë£¨∂‡∏ˆpackage”√∂∫∫≈ªÚ’ﬂ∑÷∫≈∑÷∏Ù
  type-aliases-package: com.monitor.monitorer.entity
  global-config:
  # ¬ﬂº≠…æ≥˝≈‰÷√
    logic-delete-value: 0
    logic-not-delete-value: 1
